# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)


Station.create([{ :name => 'Entremetier' },
                { :name => 'Gardemanger' },
                { :name => 'Sauccier' },
                { :name => 'Patessier' }])

Source.create([ { :name => 'sonstige' },
                { :name => 'w' },
                { :name => 'x' }])

Unit.create([ { :name => 'TL' },
              { :name => 'EL' },
              { :name => 'Msp' },
              { :name => 'Stk' },
              { :name => 'g' },
              { :name => 'kg' },
              { :name => 'ml' },
              { :name => 'cl' },
              { :name => 'l' },
              { :name => 'Zehe(n)' }])

Ingredtype.create([ { :name => 'Obst' },
                    { :name => 'Gemüse' },
                    { :name => 'Hülsenfrüchte' },
                    { :name => 'Gewürze' },
                    { :name => 'Kräuter' },
                    { :name => 'Milchprodukte' },
                    { :name => 'Fonds' },
                    { :name => 'Fleisch' },
                    { :name => 'sonstige' }])

Recipe.create([{ :station_id => 2,
                 :name => "Pesto",
                 :length => 8,
                 :ingred1 => 71,
                 :amount1 => 2,
                 :unit1 => 4,
                 :ingred2 => 68,
                 :amount2 => 1,
                 :unit2 => 1,
                 :ingred3 => 65,
                 :amount3 => 2,
                 :unit3 => 3,
                 :ingred4 => 132,
                 :amount4 => 150,
                 :unit4 => 7,
                 :ingred5 => 88,
                 :amount5 => 10,
                 :unit5 => 5,
                 :ingred6 => 29,
                 :amount6 => 2,
                 :unit6 => 10,
                 :ingred7 => 133,
                 :amount7 => 100,
                 :unit7 => 5,
                 :process => "<ol>
<li>Kr&auml;uter waschen</li>
<li>Knoblauch sch&auml;len</li>
<li>Zutaten gemeinsam p&uuml;rieren</li>
</ol><ol> </ol>",
                 :source_id => 1 }])

Ingred.create([
               # Obst
               { :name => 'Ananas', :ingredtype_id => 1 },
               { :name => 'Apfel', :ingredtype_id => 1 },
               { :name => 'Banane', :ingredtype_id => 1 },
               { :name => 'Birne', :ingredtype_id => 1 },
               { :name => 'Cumquat', :ingredtype_id => 1 },
               { :name => 'Erdbeer', :ingredtype_id => 1 },
               { :name => 'Grapefruit', :ingredtype_id => 1 },
               { :name => 'Granatapfel', :ingredtype_id => 1 },
               { :name => 'Limette', :ingredtype_id => 1 },
               { :name => 'Limone', :ingredtype_id => 1 },
               { :name => 'Mandarine', :ingredtype_id => 1 },
               { :name => 'Mango', :ingredtype_id => 1 },
               { :name => 'Melone', :ingredtype_id => 1 },
               { :name => 'Orange', :ingredtype_id => 1 },
               { :name => 'Passionsfrucht', :ingredtype_id => 1 },
               { :name => 'Stachelbeere', :ingredtype_id => 1 },
               { :name => 'Trauben grün', :ingredtype_id => 1 },
               { :name => 'Trauben rot', :ingredtype_id => 1 },
               { :name => 'Zitrone', :ingredtype_id => 1 },
               # Gemüse
               { :name => 'Aubergine', :ingredtype_id => 2 },
               { :name => 'Artischocke', :ingredtype_id => 2 },
               { :name => 'Avocado', :ingredtype_id => 2 },
               { :name => 'Bärlauch', :ingredtype_id => 2 },
               { :name => 'Blumenkohl', :ingredtype_id => 2 },
               { :name => 'Brunnenkresse', :ingredtype_id => 2 },
               { :name => 'Broccoli', :ingredtype_id => 2 },
               { :name => 'Chilli', :ingredtype_id => 2 },
               { :name => 'Chilli Habanero', :ingredtype_id => 2 },
               { :name => 'Chilli Jalapeno', :ingredtype_id => 2 },
               { :name => 'Chinakohl', :ingredtype_id => 2 },
               { :name => 'Frühlingszwiebel', :ingredtype_id => 2 },
               { :name => 'Grünkohl', :ingredtype_id => 2 },
               { :name => 'Gurke', :ingredtype_id => 2 },
               { :name => 'Hokkaido', :ingredtype_id => 2 },
               { :name => 'Ingwer', :ingredtype_id => 2 },
               { :name => 'Karotte', :ingredtype_id => 2 },
               { :name => 'Kartoffeln', :ingredtype_id => 2 },
               { :name => 'Kohlrabi', :ingredtype_id => 2 },
               { :name => 'Kürbis', :ingredtype_id => 2 },
               { :name => 'Knoblauch', :ingredtype_id => 2 },
               { :name => 'Lauch', :ingredtype_id => 2 },
               { :name => 'Maniok', :ingredtype_id => 2 },
               { :name => 'Meeretich', :ingredtype_id => 2 },
               { :name => 'Okra', :ingredtype_id => 2 },
               { :name => 'Paprika', :ingredtype_id => 2 },
               { :name => 'Pastinake', :ingredtype_id => 2 },
               { :name => 'Peperoni', :ingredtype_id => 2 },
               { :name => 'Peperoncini', :ingredtype_id => 2 },
               { :name => 'Pok Choi', :ingredtype_id => 2 },
               { :name => 'Portulak', :ingredtype_id => 2 },
               { :name => 'Rabarber', :ingredtype_id => 2 },
               { :name => 'Radischen', :ingredtype_id => 2 },
               { :name => 'Rukola', :ingredtype_id => 2 },
               { :name => 'Rotkohl', :ingredtype_id => 2 },
               { :name => 'Romanesco', :ingredtype_id => 2 },
               { :name => 'Schalotte', :ingredtype_id => 2 },
               { :name => 'Schwarzwurzel', :ingredtype_id => 2 },
               { :name => 'Spargel grün', :ingredtype_id => 2 },
               { :name => 'Spargel weiss', :ingredtype_id => 2 },
               { :name => 'Spinat', :ingredtype_id => 2 },
               { :name => 'Spitzkohl', :ingredtype_id => 2 },
               { :name => 'Steckrübe', :ingredtype_id => 2 },
               { :name => 'Süßkartoffel', :ingredtype_id => 2 },
               { :name => 'Tomate', :ingredtype_id => 2 },
               { :name => 'Wasabi', :ingredtype_id => 2 },
               { :name => 'Weißkohl', :ingredtype_id => 2 },
               { :name => 'Winterzwiebel', :ingredtype_id => 2 },
               { :name => 'Wirsing', :ingredtype_id => 2 },
               { :name => 'Wurzelpetersiilie', :ingredtype_id => 2 },
               { :name => 'Zucchini', :ingredtype_id => 2 },
               { :name => 'Gemüsezwiebel', :ingredtype_id => 2 },
               { :name => 'Zwiebel weiss', :ingredtype_id => 2 },
               { :name => 'Zwiebel rot', :ingredtype_id => 2 },
               # Hülsenfrüchte
               { :name => 'Zuckererbsen', :ingredtype_id => 3 },
               { :name => 'Feuerbohne', :ingredtype_id => 3 },
               { :name => 'Kichererbsen', :ingredtype_id => 3 },
               { :name => 'Kidney-Bohnen', :ingredtype_id => 3 },
               { :name => 'Limabohnen', :ingredtype_id => 3 },
               { :name => 'Linsen', :ingredtype_id => 3 },
               { :name => 'Mungbohnen', :ingredtype_id => 3 },
               { :name => 'Wachtelbohnen', :ingredtype_id => 3 },
               { :name => 'Weiße Bohnen', :ingredtype_id => 3 },
               { :name => '', :ingredtype_id => 3 },
               # Gewürze
               { :name => 'Anis', :ingredtype_id => 4 },
               { :name => 'Asant', :ingredtype_id => 4 },
               { :name => 'Bockhornklee', :ingredtype_id => 4 },
               { :name => 'chillies', :ingredtype_id => 4 },
               { :name => 'curryblätter', :ingredtype_id => 4 },
               { :name => 'curry Bombay', :ingredtype_id => 4 },
               { :name => 'curry Madras', :ingredtype_id => 4 },
               { :name => 'curry Thai', :ingredtype_id => 4 },
               { :name => 'Fenschelsamen', :ingredtype_id => 4 },
               { :name => 'Kapern', :ingredtype_id => 4 },
               { :name => 'Kardamom grün', :ingredtype_id => 4 },
               { :name => 'Kardamom schwarz', :ingredtype_id => 4 },
               { :name => 'Koriandersamen', :ingredtype_id => 4 },
               { :name => 'Kurkuma', :ingredtype_id => 4 },
               { :name => 'Kümmel', :ingredtype_id => 4 },
               { :name => 'Kreuzkümmel', :ingredtype_id => 4 },
               { :name => 'Kreuzkümmel schwarz', :ingredtype_id => 4 },
               { :name => 'Kreuzkümmel weiss', :ingredtype_id => 4 },
               { :name => 'Lorbeerblätter', :ingredtype_id => 4 },
               { :name => 'Nelken', :ingredtype_id => 4 },
               { :name => 'Macis', :ingredtype_id => 4 },
               { :name => 'Mohn', :ingredtype_id => 4 },
               { :name => 'Muskatnuss', :ingredtype_id => 4 },
               { :name => 'Paprika Rosen', :ingredtype_id => 4 },
               { :name => 'Paprika edelsüss', :ingredtype_id => 4 },
               { :name => 'Pfeffer bunt', :ingredtype_id => 4 },
               { :name => 'Pfeffer grün', :ingredtype_id => 4 },
               { :name => 'Pfeffer schwarz', :ingredtype_id => 4 },
               { :name => 'Pfeffer weiss', :ingredtype_id => 4 },
               { :name => 'Piment', :ingredtype_id => 4 },
               { :name => 'Safran', :ingredtype_id => 4 },
               { :name => 'Salz', :ingredtype_id => 4 },
               { :name => 'Senfkörner schwarz', :ingredtype_id => 4 },
               { :name => 'Senfkörner weiss', :ingredtype_id => 4 },
               { :name => 'Sojasauce', :ingredtype_id => 4 },
               { :name => 'Sternanis', :ingredtype_id => 4 },
               { :name => 'Süssholz', :ingredtype_id => 4 },
               { :name => 'Tamarinde', :ingredtype_id => 4 },
               { :name => 'Vanille', :ingredtype_id => 4 },
               { :name => 'Wacholderbeeren', :ingredtype_id => 4 },
               { :name => 'Wasserkresse', :ingredtype_id => 4 },
               { :name => 'Zimt', :ingredtype_id => 4 },
               { :name => 'Zucker', :ingredtype_id => 4 },
               # Kräuter
               { :name => 'Ananasminze', :ingredtype_id => 5 },
               { :name => 'Bachbunge', :ingredtype_id => 5 },
               { :name => 'Bärwurz', :ingredtype_id => 5 },
               { :name => 'Basilikum', :ingredtype_id => 5 },
               { :name => 'Beifuss', :ingredtype_id => 5 },
               { :name => 'Bohnenkraut', :ingredtype_id => 5 },
               { :name => 'Borretsch', :ingredtype_id => 5 },
               { :name => 'Brunnenkresse', :ingredtype_id => 5 },
               { :name => 'Dill', :ingredtype_id => 5 },
               { :name => 'Estragon', :ingredtype_id => 5 },
               { :name => 'Gartenkresse', :ingredtype_id => 5 },
               { :name => 'Kapuzinerkresse', :ingredtype_id => 5 },
               { :name => 'Kerbel', :ingredtype_id => 5 },
               { :name => 'Knoblauchgras', :ingredtype_id => 5 },
               { :name => 'Korianderkraut', :ingredtype_id => 5 },
               { :name => 'Lavendel', :ingredtype_id => 5 },
               { :name => 'Liebstöckel', :ingredtype_id => 5 },
               { :name => 'Lorbeer', :ingredtype_id => 5 },
               { :name => 'Löwenzahn', :ingredtype_id => 5 },
               { :name => 'Majoran', :ingredtype_id => 5 },
               { :name => 'Melisse', :ingredtype_id => 5 },
               { :name => 'Oregano', :ingredtype_id => 5 },
               { :name => 'Petersilie', :ingredtype_id => 5 },
               { :name => 'Pfefferminze', :ingredtype_id => 5 },
               { :name => 'Portulak', :ingredtype_id => 5 },
               { :name => 'Rucola', :ingredtype_id => 5 },
               { :name => 'Rosmarin', :ingredtype_id => 5 },
               { :name => 'Salbei', :ingredtype_id => 5 },
               { :name => 'Schokominze', :ingredtype_id => 5 },
               { :name => 'Selleriekraut', :ingredtype_id => 5 },
               { :name => 'Schnittlauch', :ingredtype_id => 5 },
               { :name => 'Thymian', :ingredtype_id => 5 },
               { :name => 'Waldmeister', :ingredtype_id => 5 },
               { :name => 'Wiesenkerbel', :ingredtype_id => 5 },
               { :name => 'Zitronengras', :ingredtype_id => 5 },
               { :name => 'Zitronenmelisse', :ingredtype_id => 5 },
               # Milchprodukte
               { :name => 'Butter', :ingredtype_id => 6 },
               { :name => 'Buttermilch', :ingredtype_id => 6 },
               { :name => 'Creme Fraiche', :ingredtype_id => 6 },
               { :name => 'Ghee', :ingredtype_id => 6 },
               { :name => 'Joghurt', :ingredtype_id => 6 },
               { :name => 'Quark', :ingredtype_id => 6 },
               { :name => 'Sahne', :ingredtype_id => 6 },
               # Fonds
               { :name => 'Gemüsefond', :ingredtype_id => 7 },
               { :name => 'Fischfond', :ingredtype_id => 7 },
               { :name => 'Hühnerfond', :ingredtype_id => 7 },
               { :name => 'Kalbsfond', :ingredtype_id => 7 },
               { :name => 'Rinderfond', :ingredtype_id => 7 },
               # Fleisch
               { :name => 'coc', :ingredtype_id => 8 },
               { :name => 'Entenbrust', :ingredtype_id => 8 },
               { :name => 'Kalbsrücken', :ingredtype_id => 8 },
               { :name => 'Kalbsleber', :ingredtype_id => 8 },
               { :name => 'Kalbslende', :ingredtype_id => 8 },
               { :name => 'Kaninchen', :ingredtype_id => 8 },
               { :name => 'Lamm', :ingredtype_id => 8 },
               { :name => 'Lammkotlett', :ingredtype_id => 8 },
               { :name => 'Poularde', :ingredtype_id => 8 },
               { :name => 'Poulardenbrust', :ingredtype_id => 8 },
               { :name => 'Rinderfilet', :ingredtype_id => 8 },
               { :name => 'Rinderhack', :ingredtype_id => 8 },
               { :name => 'Rinderkotlett', :ingredtype_id => 8 },
               { :name => 'Rinderlende', :ingredtype_id => 8 },
               { :name => 'Rindersteak', :ingredtype_id => 8 },
               { :name => 'Stubenkücken', :ingredtype_id => 8 },
               { :name => 'Schweinelende', :ingredtype_id => 8 },
               { :name => 'Schweinesteak', :ingredtype_id => 8 },
               { :name => 'Schweinehack', :ingredtype_id => 8 },
               { :name => 'Wachtel', :ingredtype_id => 8 },
               # Sonstige
               { :name => 'Ei', :ingredtype_id => 9 },
               { :name => 'Erdnuss', :ingredtype_id => 9 },
               { :name => 'Hanfnuss', :ingredtype_id => 9 },
               { :name => 'Haselnuss', :ingredtype_id => 9 },
               { :name => 'Kokosnuss', :ingredtype_id => 9 },
               { :name => 'Mandeln', :ingredtype_id => 9 },
               { :name => 'Nougat', :ingredtype_id => 9 },
               { :name => 'Paranuss', :ingredtype_id => 9 },
               { :name => 'Pekannuss', :ingredtype_id => 9 },
               { :name => 'Pistazie', :ingredtype_id => 9 },
               { :name => 'Zucker', :ingredtype_id => 9 },
               { :name => 'Olivenöl', :ingredtype_id => 9 },
               { :name => 'Pinienkerne', :ingredtype_id => 9 },
               { :name => 'Pistazien', :ingredtype_id => 9 },
               { :name => 'Pistazienmark', :ingredtype_id => 9 },
               { :name => 'Tongabohnen', :ingredtype_id => 9 },
               { :name => 'Wachtelei', :ingredtype_id => 9 },
               { :name => 'Walnuss', :ingredtype_id => 9 }])
